# permissions for end users to edit rdsinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rdsinstance-editor-role
rules:
- apiGroups:
  - cna.managed.openshift.io
  resources:
  - rdsinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cna.managed.openshift.io
  resources:
  - rdsinstances/status
  verbs:
  - get
